---
# tasks file for tmux-tpm
- name: mkdir {{tmux_tpm_plugins_path}}
  file:
    path: "{{tmux_tpm_plugins_path}}"
    state: directory
- name: Clone the tpm repository
  git:
    repo: "{{tmux_tpm_repo}}"
    dest: "{{tmux_tpm_plugins_path}}/tpm"
    version: "{{tmux_tpm_version}}"
